name: Build and Deploy
on:
  push:
    branches:
      - main  # Or the branch where you have your Hugo source files
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.2'  # Or the version you are using
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /Users/tangfeiwen/starter-hugo-academic/public  # 
Or your Hugo output directory

